POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": null,
    "maximumAttendees":1
}

###
POST http://localhost:3333/events/7951e93a-9757-4544-94df-ad4c203a916f/attendees
Content-Type: application/json

{
    "name":"Ana Claudia Nogueira",
    "email":"anacnogueira3@gmail.com"
}


###
GET http://localhost:3333/events/7951e93a-9757-4544-94df-ad4c203a916f


###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/3/check-in


###
GET http://localhost:3333/events/7951e93a-9757-4544-94df-ad4c203a916f/attendees?query=dsadd